---
dependencies:
  http: ^1.0.0
  http_parser: ^4.0.0
  meta: ^1.0.0
description: "'A app in Coin Galaxy.'"
dev_dependencies:
  auto_exporter: ^3.0.0
  build_runner: ^2.4.15
  test: ^1.24.0
environment:
  sdk: ^3.4.4
name: api_http
repository: https://github.com/normidar/api_http
version: 0.0.1
